### ISSUE TITLE
Doesn't persist the progress of lesson between sessions

### ISSUE THREAD

**Issue by wolfch** [WardCunningham/morse#10]
By "session" I mean from when the app is started until exited.  Currently, during a session, the progress of the student is tracked based on pass/fail score; I believe maybe this is in-memory in a class named `Lesson`, but not sure.  In any case, if the app is exited then restarted, the training starts all over again from the beginning, so the student has to repeat lessons learned.

Unfortunately, without persisting the progress and picking up where left off, this app is very limited compared to what it could be.

**Comment by WardCunningham** [comment]
The program depends on short-term memory to create an enhanced practice effect. The program need not remember past performance any longer than the student. A day of other activity, or maybe even an hour of unrelated acoustic discrimination, is enough to justify a reset. The program does have an automatic accelerated introduction rate that persists until error rates climb. I built computer models of this effect in the '70s then tested the parameters on real students. The bar graph output exists in the program as a means for me to align modeled and human learning rates that informed my threshold settings.

**Comment by wolfch** [comment]
>A day of other activity, or maybe even an hour of unrelated acoustic discrimination, is enough to justify a reset.
 
I think that's a subjective matter of opinion.   I still think its a great application and I still use it.  I discovered I can add/remove practice characters which is good enough for me to adjust the session.  Thanks for a great app!

**Comment by wolfch** [comment]
> I think that's a subjective matter of opinion. 

Nope - after using your app and the other iPhone app which resumes from last session.  I have to admit: you're right after all!  My bad!
